system:
  title: 'サロン評価調査'
  url: 'https://salon-review.com/'
  bbs_url: 
  trello_url: 
  google_form_url: 'https://docs.google.com/forms/d/e/1FAIpQLSfHujRENXVPxVFVTArWZOrKZdGYyJsTSMOgJrvCbyPhFU_yxQ/viewform?usp=sf_link'
  official_twitter_id: 'salon-review'
  description: 'サロンの評価を投稿しよう！'
  hashtag: 'サロン評価調査'
  twitter_site: newburu
  twitter:
    url: 'https://twitter.com/'
    tweet_url: 'http://twitter.com/intent/tweet'
    share_url: 'http://twitter.com/share'
  facebook:
    share_url: 'https://www.facebook.com/share.php'
  line:
    share_url: 'https://social-plugins.line.me/lineit/share'
  mail:
    share_url: 'mailto:'
  default:
    user_name: 名無しさん
    rail_color: '#0000ff'
    imakoko_kind: 0
  const:
    on_str: 'on'
    off_str: 'off'
